wirte article about a oscilloscope
libmcu/blog pull request #1
Opened 2022-11-18 01:06 UTC by Wizmik187

오실로스코프 bandwidth에 관한 article 입니다.

2022-11-18 01:07 UTC, Wizmik187 commented
browser 에서 어떻게 보이는지 확인은 안했습니다. 한번 확인 부탁드리겠습니다.

2022-11-18 03:17 UTC, onkwon requested changes
- 참고로 http://speller.cs.pusan.ac.kr/ 에서 맞춤법 및 띄어쓰기 검사할 수 있어요
- 대역폭과 고조파는 이미 잘 알려져있는 번역이니까 한글로 적는 게 더 잘 읽히지 않을까요?
- 다음과 같은 구조로 기술적인 내용을 조금만 더 추가하면 어떨까요?

```
## 오실로스코프 역할
## 대역폭에 대한 이해
오실로스코프에서 말하는 대역폭이란
### 아날로그 신호
### 디지털 신호
## 대역폭 선택 기준
```

2022-11-18 03:17 UTC, onkwon commented on content/posts/oscilloscope-bandwidth/index.kr.md
> +date: 2021-11-18
2021년 -> 2022년

2022-11-18 03:17 UTC, onkwon commented on content/posts/oscilloscope-bandwidth/index.kr.md
> +![3db](3db.png)
이미지 출처 밝혀야하지 않을까요?

2022-11-18 03:17 UTC, onkwon commented on content/posts/oscilloscope-bandwidth/index.kr.md
> +description: 오실로스코프의 필수 성능인 Bandwidth 에 대하여 알아보자.
오실로스코프의 필수 성능 지표인 Bandwidth에 대하여 알아보자 는 어떨까요?

2022-11-19 00:11 UTC, Wizmik187 commented
좀더 글을 다듬은 후에 PR 올리겠습니다.

2022-11-19 00:11 UTC, closed without merging